#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:nil arch:headline
#+OPTIONS: author:t c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t title:t toc:nil todo:t
#+OPTIONS: |:t
#+TITLE: README
#+DATE: <2016-11-06 Sun>
#+AUTHOR: Kang Tu
#+EMAIL: tninja@Pengs-MacBook-Pro.local
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.1 (Org mode 8.3.6)

* What is Lilypond?

- https://en.wikipedia.org/wiki/LilyPond
- http://lilypond.org/

* Quick start

** Install stuffs needed

*** required softwares

- use lyp: https://github.com/noteflakes/lyp
  - lyp install lilypond. Currently it is 18.20
  - uninstall homebrew gs, use lyp version of gs
- homebrew version is inactive now :(.
  - homebrew cask version of lilypond: brew cask install lilypond (however 19 version *NOT* working)
- timidity (command line tool to play midi): brew install timidity

*** soundfonts (optional, if you want a better midi library than system default you might want to try this)

- https://musescore.org/zh-hans/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/soundfont-%E9%9F%B3%E8%89%B2%E5%BA%93
- https://zdoom.org/wiki/Sound_fonts
- http://timidity.s11.xrea.com/files/readme_cfgp.htm
- http://www.synthfont.com/soundfonts.html
- best soundfont? https://musescore.org/en/node/103046

- Update timidity configuration to use downloaded soundfonts
  - modify the timidity.cfg to make it looks like

#+begin_example
  dir /Users/tninja/local/usr/share/soundfonts/
  soundfont FluidR3_GM.sf2
#+end_example

** Get music score resources

*** [[https://musescore.com][Musescore]]

- Install musescore: (to convert musescore file format to lilypond)
 
**** Examples

- 10000 reasons: https://musescore.com/user/442966/scores/1183611
- ryu theme: https://musescore.com/user/2960946/scores/950351
- lost painting from castlevania: https://musescore.com/user/9475036/scores/2683096

**** Download and convert to lilypond mode

Firstly download mscz file format

#+name: convert
#+BEGIN_SRC shell
## Convert to xml
/Applications/MuseScore\ 2.app/Contents/MacOS/mscore The_Lost_Painting_from_Castlevania_Symphony_of_the_Night.mscz -o The_Lost_Painting_from_Castlevania_Symphony_of_the_Night.xml

## Convert to .ly: lilypond
musicxml2ly The_Lost_Painting_from_Castlevania_Symphony_of_the_Night.xml

#### Modify the file to fix the problem

## Compile the .ly and generate midi
lilypond -dmidi-extension=mid The_Lost_Painting_from_Castlevania_Symphony_of_the_Night.ly 
#+END_SRC

* Lilypond
  
** Install

- use lyp: https://github.com/noteflakes/lyp
  - lyp install lilypond. Currently it is 18.20
  - uninstall homebrew gs, use lyp version of gs
- homebrew version is inactive now :(.

** Emacs

- (Yet to explore) lilypond-mode.el, which is available in lilypond installation

*** How to use lilypond-mode

- play the whole buffer: C-c RET

- play code chunk in midi?

** org-mode integration

- (Yet to explore) http://orgmode.org/worg/org-contrib/babel/languages/ob-doc-lilypond.html

#+begin_src lilypond :file Mixolydian.pdf
  \relative c' { 
	g a b c d e f g f e d c b a g a b c d e f g f e d c b a g1 
  }
#+end_src

#+results:
[[file:Mixolydian.pdf]]

#+begin_src lilypond :file Twotiger.pdf
  global = {
	\key c \major
	\time 2/4
  }

  upper = \absolute {
	\clef "bass"
	c8 d8 e8 c8 | c8 d8 e8 c8 | e8 f8 g4 | e8 f8 g4
	g16 a16 g16 f16 e8 c8 | g16 a16 g16 f16 e8 c8 | c8 g,8 c4 | c8 g,8 c4 
  }

  lower_motif = \absolute { c,8 g,8 c,8 g,8 }

  lower = \absolute {
	\clef "bass"
	\lower_motif | \lower_motif | \lower_motif | \lower_motif
	\lower_motif | \lower_motif | \lower_motif | c,8 g,8 c,4 
  }

  %% aligning lyrics to a melody: http://lilypond.org/doc/v2.19/Documentation/learning/aligning-lyrics-to-a-melody
  %% 每一个单词/中文字 对一个音符
  verse = \new Lyrics \lyricsto "one" {
	\lyricmode {
	  两 只 老 虎 | 两 只 老 虎 | 跑 得 快 | 跑 得 快
	  一 只 没 有 耳 朵 | 一 只 没 有 尾 巴 | 真 奇 怪 | 真 奇 怪
	}
  }

  \score
  {
	\new PianoStaff
	<<
	  \set PianoStaff.instrumentName = "Piano"
	  \new Voice = "one" {
		\upper
	  }
	  \new Voice = "two" {
		\lower
	  }
	  \verse
	>>
	\midi { }
	\layout { }
  }
#+end_src

#+results:
[[file:Twotiger.pdf]]
